# GoReleaser configuration
version: 2

builds:
  - binary: projman
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/SalvatoreSpagnuolo-BipRED/projman/cmd.Version={{.Version}}
    flags:
      - -trimpath

archives:
  - name_template: "projman-{{ .Os }}-{{ .Arch }}"
    rlcp: true
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - RELEASE.md

checksum:
  disable: true

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^chore:"
      - "^docs:"
      - "^test:"
      - "^ci:"
  groups:
    - title: Features
      regexp: "^feat"
      order: 0
    - title: Bug Fixes
      regexp: "^fix"
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: SalvatoreSpagnuolo-BipRED
    name: projman
  prerelease: auto
  make_latest: true
  name_template: "{{.Tag}}"
